# Generated by Django 5.0.4 on 2024-05-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('status', models.CharField(default='MP', max_length=3)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.course')),
            ],
        ),
    ]
